# Generated by Django 6.1.1 on 2026-09-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_rename_registrations_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
